[package]
name = "node-rs"
version = "0.1.0"
authors = ["Andrew Gaspar <andrew.gaspar@outlook.com>"]
license = "MIT"
description = "Rust bindings for node.js using stdweb"

[dependencies]
stdweb = "0.4.8"
stdweb-derive = "0.4.0"